In [2]:
import numpy as np
import pandas as pd
# 1) Numpy’da Vektor ve Matrisin farkini tek cumle ile ifade ediniz.

# Numpy dizileri tek boyutlu (vektör) veya çok boyutlu (matris) olabilir.

In [3]:
# 2) 10 elemanli bir listeden NumPy Array’i olusturunuz.

list = []
for i in range(10):
    list.append(i)

na = np.array(list)
print(na)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3) Icerisinde ‘0’ lar olan, ve veri tipi integer olan 10X10’luk bir matris olusturunuz.
np.zeros((10,10), dtype=int) 

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [5]:
# 4) Icerisinde ‘1’ ler olan, veri tipi float olan 10X10’luk bir matris olusturunuz.
np.ones((10,10), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# 5) Icerisinde ‘9’ lar olan, veri tipi integer olan 10X10’luk bir matris olusturunuz.

np.full((10,10),9)

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [7]:
# 6) 5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array olusturunuz.
np.arange(5,25,3)

array([ 5,  8, 11, 14, 17, 20, 23])

In [8]:
# 7) -1 ile 1 arasinda 30 adet Array olusturunuz.
np.linspace (0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [9]:
# 8) 0 ile 30 arasinda 5x6’lik bir matris olusturun.
np.random.randint(0,30,(5,6))

array([[24, 11, 24, 26, 26, 15],
       [25, 28,  2,  3, 14, 19],
       [17,  0, 29, 12,  4, 27],
       [24, 11, 11,  2, 17,  6],
       [24, 19, 14, 23, 28, 20]])

In [10]:
# 9) Kosegenleri 1 olan 10x10’luk bir matris olusturunuz.

np.full((10,10),1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [11]:
#10) 0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;
#eleman sayisini
#boyut bilgisini/sayisini
#satir X sutun bilgisini
#veri tipini numpy metodlariyla yazdiriniz.

matris = np.random.randint(0,10,(5,10))
print(matris)
#eleman sayisini
print(matris.size)
#boyut bilgisini/sayisini
print(matris.ndim)
#satir X sutun bilgisini
print(matris.shape)
#veri tipini numpy metodlariyla yazdiriniz.
print(matris.dtype)





[[5 3 2 7 8 3 2 0 6 1]
 [3 5 7 9 6 0 8 1 9 5]
 [6 5 2 9 7 1 0 6 5 4]
 [2 4 9 0 1 0 2 7 8 0]
 [6 1 1 6 9 8 8 6 7 5]]
50
2
(5, 10)
int32


In [12]:
# 11) 0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris olusturunuz. (3 boyutlu bir matris olusturulacak)
matris = np.random.randint(0,10,(3,4,7))
print(matris)


[[[6 4 4 7 8 6 3]
  [6 6 2 5 7 0 8]
  [7 1 3 9 6 1 5]
  [5 6 4 2 1 2 7]]

 [[0 6 2 7 4 6 1]
  [5 4 7 9 6 6 9]
  [4 1 2 8 9 1 6]
  [2 8 5 0 2 3 1]]

 [[0 3 1 4 1 5 1]
  [2 5 7 7 0 6 1]
  [9 0 7 0 0 4 7]
  [3 6 8 2 0 2 3]]]


In [13]:
# 12) Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz. (boyut sayisini degistirin.)

list = [i for i in range(10)]
vektor = np.array(list)
matris = vektor.reshape(2,5)
print(matris)




[[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
# 13) 4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz.
arr1 = np.random.randint(10, size=4)
arr2 = np.random.randint(10, size=4)
arr3 = np.random.randint(10, size=4)
arr4 = np.random.randint(10, size=4)
union_arr = np.concatenate([arr1,arr2,arr3,arr4])
print(union_arr)

[4 9 3 3 7 5 8 3 1 2 1 1 7 4 7 2]


In [15]:
#14) 2 boyutlu bir matris ve bir vektör olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

matris_1 = np.random.randint(30, size=(5,2))
print((matris_1))
vektor_1 = np.random.randint(30, size=(5,1))
print((vektor_1))
union_1 = np.concatenate([matris_1,vektor_1], axis = 1)
print(union_1)



[[ 6 27]
 [25 14]
 [21 17]
 [24 22]
 [19 22]]
[[28]
 [ 4]
 [15]
 [ 9]
 [16]]
[[ 6 27 28]
 [25 14  4]
 [21 17 15]
 [24 22  9]
 [19 22 16]]


In [16]:
# 15) Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

print ("axis = 0 y ekseni yani sutun")
print ("axis = 1 x ekseni yani satırdır")

axis = 0 y ekseni yani sutun
axis = 1 x ekseni yani satırdır


In [17]:
# 16) Farkli boyutlardaki arraylari satin ve sutun bazli ayri ayri birlestiriniz.

arr1 = np.random.randint(10, size=(5,2))
print(arr1)
arr2 = np.random.randint(10, size=(5,4))
print(arr2)
total1 = np.concatenate((arr1,arr2), axis = 1)
total0 = np.concatenate((arr1,arr2), axis = 1)
print(total1)
print("*******************")
print(total1)

[[0 2]
 [4 0]
 [8 5]
 [1 3]
 [7 8]]
[[3 7 6 6]
 [3 7 8 2]
 [3 4 3 8]
 [3 7 1 1]
 [2 4 9 4]]
[[0 2 3 7 6 6]
 [4 0 3 7 8 2]
 [8 5 3 4 3 8]
 [1 3 3 7 1 1]
 [7 8 2 4 9 4]]
*******************
[[0 2 3 7 6 6]
 [4 0 3 7 8 2]
 [8 5 3 4 3 8]
 [1 3 3 7 1 1]
 [7 8 2 4 9 4]]


In [18]:
# 17) 10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 5 ayri array olusturunuz.

list = [i for i in range(10)]
np_list = np.array(list)
array5= np.split(np_list, [2,3,7,9])
print(array5)


[array([0, 1]), array([2]), array([3, 4, 5, 6]), array([7, 8]), array([9])]


In [19]:
# 18) Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan 
# sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

arr1 = np.random.randint(6, size=(6))
sorted_arr1 = np.sort(arr1)

array_copy = np.sort(sorted_arr1)[::-1]
print(array_copy)

for i in arr1:
    print(array_copy[i])





[4 3 1 0 0 0]
4
4
0
3
0
4


In [20]:
# 19) 20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

arr1 = np.random.randint(100, size=(20))
print(arr1)
print(arr1[2],arr1[4],arr1[6])


[32 95 26 25 35 79 63 78 81 86 55 55  4 96 13 28 87 74 22 41]
26 35 63


In [24]:
# 20) 10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.
arr1 = np.random.randint(100, size=(10))
print(arr1)
arr1[3] = 100
print(arr1)

[18 56 11 13 54 62 60 10 71  7]
[ 18  56  11 100  54  62  60  10  71   7]


In [22]:
# 21) “Diagonal Matrix” ve “Trace of Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

# Diagonal Matrix = ilkköşegenin dışında kalan girişlerin tümü sıfır ve genellikle kare matris olan bir matrisdir. 
# Trace of Matrix = matrisin ana köşegen elemanlarının toplamıdır.

In [23]:
# 22) 5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.(ayri ayri)

arr = np.arange(25).reshape((5,5))
#print(arr)
x = np.diag(arr)
np.diag(x, k=1)
np.diag(x, k=-1)
y= np.diag(x)
print(y)



for i in range(len(arr)):
    for j in range (len(arr)):
        if i == j :
            print(i,j,arr[i,j]) 




[[ 0  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0 12  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 24]]
0 0 0
1 1 6
2 2 12
3 3 18
4 4 24


In [28]:
# 23) 10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.
arr1 = np.random.randint(10,20, size=(10))
print(arr1[3:])

[16 13 16 17 17 19 11 12 11 10]
[17 17 19 11 12 11 10]


In [79]:
# 24) 10X10 luk bir matris olusturunuz ve ;
arr1 = np.random.randint(10,20, size=(10,10))
print(arr1)
print("-----------------------------------------------------")
# 3.satir ve 5.sutuna ulasiniz.
print(arr1[3:4])
#print("-----------------------------------------------------")
print(arr1[0:, [5]])
#print("-----------------------------------------------------")
# 5.sutunun tum satirlarina ulasiniz.
print(arr1[0:, [5]])
#print("-----------------------------------------------------")
# Tum sutunlarin 2.satirlarina ulasiniz.
print(arr1[2,:])
print(arr1[2:3])
print("-----------------------------------------------------")
# tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.
print(arr1[2:7])
print("-----------------------------------------------------")
# satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.
print(arr1[2:5,3:7])
print("-----------------------------------------------------")
# satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.
print(arr1[5:,0:4])
print("-----------------------------------------------------")
# sutun indexi sadece 3, 6, 9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.
print(arr1[0:,[3,6,9]])
print("-----------------------------------------------------")
# 5.indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz."""
arr1[5,5]="01121986"
print(arr1)



[[15 12 19 11 10 12 18 18 17 15]
 [12 16 19 16 14 11 19 13 13 17]
 [16 17 10 10 10 16 11 14 12 13]
 [16 16 18 12 13 13 19 16 17 13]
 [17 12 15 16 19 12 12 12 12 14]
 [13 16 18 15 14 10 16 15 17 13]
 [15 16 12 18 19 16 13 12 13 11]
 [19 17 12 13 10 16 18 18 14 15]
 [18 18 13 10 18 12 16 15 10 12]
 [16 16 18 17 14 15 12 15 13 13]]
-----------------------------------------------------
[[16 16 18 12 13 13 19 16 17 13]]
[[12]
 [11]
 [16]
 [13]
 [12]
 [10]
 [16]
 [16]
 [12]
 [15]]
[[12]
 [11]
 [16]
 [13]
 [12]
 [10]
 [16]
 [16]
 [12]
 [15]]
[16 17 10 10 10 16 11 14 12 13]
[[16 17 10 10 10 16 11 14 12 13]]
-----------------------------------------------------
[[16 17 10 10 10 16 11 14 12 13]
 [16 16 18 12 13 13 19 16 17 13]
 [17 12 15 16 19 12 12 12 12 14]
 [13 16 18 15 14 10 16 15 17 13]
 [15 16 12 18 19 16 13 12 13 11]]
-----------------------------------------------------
[[10 10 16 11]
 [12 13 13 19]
 [16 19 12 12]]
-----------------------------------------------------
[[13 16 18 15]
 [15

In [93]:
# 25) 0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) ve numpy metodlariyla asagidaki islemleri uygulayin;
arr1 = np.arange(0,50,5)
print(arr1)
# 20 den buyuk olan kac deger var.
print(len(arr1[arr1>20]))
# 30’dan kucuk kac deger var
print(len(arr1[arr1<30]))
# icerisinde 33 gecen kac deger var
print(len(arr1[arr1>32]))
# olusturulan arrayin tum elemanlarini 5 ile carpin.
print(arr1*5)
# olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.
print(arr1%2)

[ 0  5 10 15 20 25 30 35 40 45]
5
6
3
[  0  25  50  75 100 125 150 175 200 225]
[0 1 0 1 0 1 0 1 0 1]


In [108]:
# 26) 0 ile 1 arasinda 50 elamanli bir array olusturunuz ve;

arr1 = np.linspace(0,1,50)
print(arr1)
print("*****************************")
# orlamasini aliniz.
print(np.mean(arr1))
print("*****************************")
# standart sapmasini aliniz.
print(np.std(arr1))
print("*****************************")
# varyansini aliniz.
print(np.var(arr1))
print("*****************************")
# median’ini aliniz.
print(np.median(arr1))
print("*****************************")
# en kucuk degeri bulunuz.
print(np.min(arr1))
print("*****************************")
# en buyuk degeri bulunuz.
print(np.max(arr1))

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
*****************************
0.5
*****************************
0.2945075446869757
*****************************
0.086734693877551
*****************************
0.5
*****************************
0.0
*****************************
1.0


In [ ]:
# 27)Pandas seriler ve numpy arrayler arasindaki farklar nelerdir yaziniz.
""" Seriler Numpy dizileri baz alınarak oluşturuldukları için onlara çok benzerler. 
Seri, etiketli verilerden oluşan tek boyutlu bir veri yapısıdır. Etiket değerlerine ise indeks denir. 
Verinin kendisi sayılar, dizeler veya başka Python objelerinden oluşabilir. 
Serileri oluşturmak için ise listeler, sıralı diziler ya da sözlükler kullanılabilir. """